hyperparameters: 
  data_path: 'data/processed/'
  out_features: 5
  Linear_features: 2048
  learning_rate: 0.0001
  epochs: 2
  weight_decay: 0.01
  
  num_workers: 6
  project_name: "the-best-DeiT-FER"
  user: "thebestofthebest"
  seed: 1234
  